import type { NextPage } from 'next'
import Head from 'next/head'
import { DailyPick } from '../components/dailyPick/DailyPick';
import { Card } from '../components/card/Card';
import { Premium } from '../components/premium/Premium';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Homepage generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Podcast</h1>

        <DailyPick
          name="Daily Pick"
          heading2="sleep with me bedtime stories"
          description="Train your mind for a happier, healthier life"
          src="/arrow.png"
          alt="Arrow"
          btnLabel="Let's start"
        />

        <h3 className={styles.heading3}>Wellness</h3>

        <div className={styles.grid}>
          <Card
            id="beyond_fear"
            label="New"
            title="Beyond Living Fear"
            postedAgo="15 minutes"
          />
          <Card
            id="twilight_zone"
            title="The Twilight Zone"
            postedAgo="15 minutes"
          />
          <Card
            id="retrain_brain"
            label="New"
            title="Retrain Your Brain"
            postedAgo="15 minutes"
          />

          <Card
            id="meditation_lullaby"
            title="A Medidation Lullaby"
            postedAgo="15 minutes"
          />

        </div>

        <Premium
          title="GO PREMIUM"
          subtitle="Time to unlock full library"
          btnLabel="Go Premium"
          src="/add_button.png"
          alt="Add Button"
        />

      </main>

    </div>
  )
}

export default Home
