import type { NextPage } from 'next'
import Link from 'next/link';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Homepage generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.heading1}>
          Podcast
        </h1>

        <div className={styles.daily_pick}>
          <div className={styles.bgImages}>
          </div>
          <div className={styles.content}>
            <span className={styles.name}>Daily Pick</span>
            <h2 className={styles.heading2}>sleep with me<br /> bedtime stories</h2>
            <p className={styles.description}>
              Train your mind for a happier, healthier life
            </p>

            <button className={styles.startBtn}><Image src="/arrow.png" alt="Arrow" width={15} height={12} /><span className={styles.arrowBtn}>Let's start</span></button>
          </div>
        </div>

        <h3 className={styles.heading3}>Wellness</h3>

        <div className={styles.grid}>
          <div className={styles.card}>
            <div className={styles.imgCard}>
              <div className={styles.label}>New</div>
            </div>
            <div className={styles.title}>Living Beyond Fear</div>
            <span className={styles.postedAgo}>15 minutes</span>
          </div>

          <div className={styles.card}>
            <div className={styles.imgCard}>
            </div>
            <div className={styles.title}>The Twilight Zone</div>
            <span className={styles.postedAgo}>15 minutes</span>
          </div>

          <div className={styles.card}>
            <div className={styles.imgCard}>
              <div className={styles.label}>New</div>
            </div>
            <div className={styles.title}>Retrain your brain</div>
            <span className={styles.postedAgo}>15 minutes</span>
          </div>

          <div className={styles.card}>
            <div className={styles.imgCard}>
            </div>
            <div className={styles.title}>A Mediatation Lullaby</div>
            <span className={styles.postedAgo}>15 minutes</span>
          </div>
        </div>

        <div className={styles.premium}>
          <h4 className={styles.heading4}>GO PREMIUM</h4>
          <div className={styles.subheading}>Time to unlock full library</div>
          <button className={styles.primaryBtn}>Go Premium</button>
        </div>
      </main>

    </div>
  )
}

export default Home
